tracer.property: "I AM THE DEFAULT"
spring.datasource.platform: "postgres"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/eagle_eye_local"
spring.datasource.username: "postgres"
spring.datasource.password: ""
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring:
  jpa:
    show-sql: "true"
    database: "POSTGRESQL"
    properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: "true"
    hibernate.ddl-auto: "update"